### ISSUE TITLE
install failed on node v10

### ISSUE THREAD

**Issue by wareczek** [IjzerenHein/node-web-bluetooth#3]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-52-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/test-bt/node_modules/bluetooth-hci-socket
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

**Comment by IjzerenHein** [comment]
The problem is not with node-web-bluetooth, but with a dependency. In this case `bluetooth-hci-socket`

**Comment by wareczek** [comment]
Ok, there is open issue: https://github.com/noble/node-bluetooth-hci-socket/issues/112
